/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from 'util';
import Ajv = require('ajv');
import { GuideImageInputObjects } from '../../types/http/admin/guide-images';
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export { GuideImageInputObjects };
export const GuideImageInputObjectsSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  definitions: {
    'Pick<GuideImageEntryObject,"weight"|"id">': {
      defaultProperties: [],
      properties: {
        id: {
          type: 'string',
        },
        weight: {
          type: 'number',
        },
      },
      required: ['id', 'weight'],
      type: 'object',
    },
  },
  items: {
    $ref: '#/definitions/Pick<GuideImageEntryObject,"weight"|"id">',
  },
  type: 'array',
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, 'errors'>;
export const isGuideImageInputObjects = ajv.compile(
  GuideImageInputObjectsSchema
) as ValidateFunction<GuideImageInputObjects>;
export default function validate(value: unknown): GuideImageInputObjects {
  if (isGuideImageInputObjects(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(
        isGuideImageInputObjects.errors!.filter((e: any) => e.keyword !== 'if'),
        { dataVar: 'GuideImageInputObjects' }
      ) +
        '\n\n' +
        inspect(value)
    );
  }
}
