---
- name: Add redis-server repository
  shell: | 
    curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
  args:
    warn: no

- name: Install redis-server
  apt:
    name: redis-server
    state: latest
    update_cache: yes

- name: Allow interaction with systemd
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'supervised systemd'
    regexp: '^supervised'
    state: present

# This will not work if the bind directive is commented out
# but since we can assume we're working with the default
# redis.conf this should be OK

- name: Set bind addresses
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'bind {{ redis.bindAddresses }}'
    regexp: '^bind'
    state: present
  when: redis.bindAddresses is defined

- name: Comment out bind directive (listen on all interfaces) 
  lineinfile:
    dest: /etc/redis/redis.conf
    line: '# bind 127.0.0.1 ::1'
    regexp: '^bind'
    state: present
  when: redis.bindAddresses is undefined

- name: Set protected mode
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'protected-mode {{ redis.protectedMode }}'
    regexp: '^protected-mode'
    state: present

- name: Restart redis-server service
  service:
    name: redis-server
    state: restarted
    enabled: yes
