---
- name: Add redis-server repository
  apt_repository:
    repo: ppa:chris-lea/redis-server
    state: present
    mode: '644'

- name: Install redis-server
  apt:
    name: redis-server
    state: latest
    update_cache: yes

- name: Allow interaction with systemd
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'supervised systemd'
    regexp: '^supervised'
    state: present

# This will not work if the bind directive is commented out
# but since we can assume we're working with the default
# redis.conf this should be OK

- name: Set bind addresses
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'bind {{ redis.bindAddresses }}'
    regexp: '^bind'
    state: present
  when: redis.bindAddresses is defined

- name: Comment out bind directive (listen on all interfaces) 
  lineinfile:
    dest: /etc/redis/redis.conf
    line: '# bind 127.0.0.1 ::1'
    regexp: '^bind'
    state: present
  when: redis.bindAddresses is undefined

- name: Set protected mode
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'protected-mode {{ redis.protectedMode }}'
    regexp: '^protected-mode'
    state: present

- name: Restart redis-server service
  service:
    name: redis-server
    state: restarted
