import type { LocaleMessageObject } from 'vue-i18n';

const user: LocaleMessageObject = {
  _: 'Profile',
  title: 'Profile',
  info: 'Information',
  access: 'Access',
  settings: 'Settings',

  name: 'Name',
  email: 'Email',
  phone: 'Phone',
  permissions: 'Assigned permissions',
  roles: 'Assigned roles',

  languages: {
    _: 'Language',
    title: 'Languages',
  },

  mfa: {
    _: 'MFA',
    title: 'Multi-factor authentication',
    enable: 'Enable multi-factor authentication',
    disable: 'Disable multi-factor authentication',
    disabled: 'Multi-factor authentication is disabled, please add a device to enable it.',
    devices: {
      _: 'Device',
      title: 'Devices',
      add: 'Add device',
      remove: 'Remove device',
      none: 'No multi-factor authentication device registered.',
      name: {
        _: 'Device name',
        title: 'Enter device name',
      },
      preferred: {
        _: 'Preferred',
        promote: 'Promote as preferred?',
        promoteConfirm: 'Promote {name} as preferred?',
      },
      init: {
        _: 'Initialize',
        title: 'Initialize device',
      },
      qr: {
        title: 'Scan QR code and verify',
        text: 'Scan the QR code with your authenticator app and enter the code below.',
      },
      registered: 'Device successfully registered',
      verify: 'Verify device',
    },
    providers: {
      _: 'Provider',
      title: 'Providers',
      otp: {
        _: 'OTP',
        title: 'One-time password',
        description:
          'One-time passwords generated by authenticator app. Supported apps: Google Authenticator, Microsoft Authenticator, Authy, Duo Security etc.',
      },
      fido: {
        _: 'FIDO',
        title: 'FIDO / WebAuthn',
        description:
          'WebAuthn / FIDO2-compliant devices. Supported devices: hardware keys, Windows Hello, Face ID etc.',
      },
      duo: {
        _: 'Duo',
        title: 'Duo Security',
        description:
          'Duo Security is a cloud-based multi-factor authentication provider. Make sure your account (email) is enrolled in Duo Security before adding this device.',
      },
    },
  },
};

export default user;
