packages:
  - apps/**
  - packages/**
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - es5-ext
  - esbuild
  - json-editor-vue
  - msgpackr-extract
  - puppeteer
  - sharp
  - simple-git-hooks
  - vue-demi
