---
- name: Add Node.js 18 LTS repository
  shell: 'curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -'
  args:
    warn: no

- name: Install latest Node.js
  apt:
    name: nodejs
    state: latest
    update_cache: yes
