---
- name: Add Node.js signing key
  shell: 'curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg'
  args:
    warn: no

- name: Add Node.js repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main'
    state: present
    filename: nodesource
    mode: '644'

- name: Install latest Node.js
  apt:
    name: nodejs
    state: latest
    update_cache: yes
