version: '3.8'

name: intake24-dev

services:
  db:
    image: postgres:16-alpine
    container_name: intake24-db
    restart: always
    env_file:
      - ../apps/api/__tests__/.env-test
      - ../apps/api/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - data-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: intake24-redis
    restart: always
    env_file:
      - ../apps/api/.env
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - data-redis:/data

volumes:
  data-db:
  data-redis:
