name: intake24-dev

services:
  db:
    image: postgres:17-alpine
    container_name: intake24-db
    restart: always
    env_file:
      # optionally used for local development to load environment variables for init scripts
      - path: ../apps/api/__tests__/.env-test
        required: false
      - path: ../apps/api/.env
        required: false
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - data-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: intake24-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - data-redis:/data

volumes:
  data-db:
  data-redis:
