- name: '{{ app|upper }} | Include shared vars'
  include_vars: '../instances/{{ instance }}/shared/config.json'

- name: '{{ app|upper }} | Create / check group'
  group:
    name: '{{ env.group }}'
    state: present

- name: '{{ app|upper }} | Create / check user'
  user:
    name: '{{ env.user }}'
    group: '{{ env.group }}'

- name: '{{ app|upper }} | Install pnpm to latest'
  command: npm install -g pnpm

- name: '{{ app|upper }} | Create / check application directory'
  file:
    path: '{{ env.directory }}'
    state: directory
    owner: '{{ env.user }}'
    group: '{{ env.group }}'

- name: '{{ app|upper }} | Checkout source from git repository'
  become_user: '{{ env.user }}'
  git:
    dest: '{{ env.directory }}'
    repo: '{{ git.repository }}'
    version: '{{ git.branch }}'
    force: yes
    accept_hostkey: true

- name: '{{ app|upper }} | Install dependencies'
  become_user: '{{ env.user }}'
  command: pnpm install
  args:
    chdir: '{{ env.directory }}'
