- name: '{{ app|upper }} | Include shared vars'
  include_vars: '../instances/{{ instance }}/shared/config.json'

- name: '{{ app|upper }} | Settings init facts'
  set_fact:
    git_version: '{{ version | default (git.branch, true) }}'

- name: '{{ app|upper }} | Deployment started | Instance: {{ instance }} | Version: {{ git_version }}'
  community.general.slack:
    channel: '{{ slack.channel }}'
    token: '{{ slack.token }}'
    msg: '🚀 Deployment started | *Instance:* {{ instance }}, *Version (branch/tag):* <https://github.com/intake24/intake24/tree/{{ git_version }}|{{ git_version }}>'

- name: '{{ app|upper }} | Create / check group'
  group:
    name: '{{ env.group }}'
    state: present

- name: '{{ app|upper }} | Create / check user'
  user:
    name: '{{ env.user }}'
    group: '{{ env.group }}'

- name: '{{ app|upper }} | Create / check application directory'
  file:
    path: '{{ env.directory }}'
    state: directory
    owner: '{{ env.user }}'
    group: '{{ env.group }}'

- name: '{{ app|upper }} | Checkout source from git repository'
  become_user: '{{ env.user }}'
  git:
    dest: '{{ env.directory }}'
    repo: '{{ git.repository }}'
    version: '{{ git_version }}'
    force: yes
    accept_hostkey: true

- name: '{{ app|upper }} | Install pnpm'
  become_user: '{{ env.user }}'
  command: corepack install
  args:
    chdir: '{{ env.directory }}'

- name: '{{ app|upper }} | Install dependencies'
  become_user: '{{ env.user }}'
  command: pnpm install
  args:
    chdir: '{{ env.directory }}'
