- name: '{{ app|upper }} | Update pm2 to latest'
  command: npm install -g pm2

- name: '{{ app|upper }} | Update pm2 in-memory code'
  become_user: '{{ env.user }}'
  command: pm2 update

- name: '{{ app|upper }} | Copy .env config file'
  become_user: '{{ env.user }}'
  copy:
    src: '{{ apps[app].env_file }}'
    dest: '{{ env.directory }}/{{ apps[app].path }}/.env'
    mode: '644'

- name: '{{ app|upper }} | Copy pm2 config file'
  become_user: '{{ env.user }}'
  copy:
    src: '{{ apps[app].pm2_file }}'
    dest: '{{ env.directory }}/{{ apps[app].path }}/ecosystem.config.js'
    mode: '644'

- name: '{{ app|upper }} | Build API server'
  become_user: '{{ env.user }}'
  command: pnpm build
  args:
    chdir: '{{ env.directory }}/{{ apps[app].path }}'

- name: '{{ app|upper }} | Run system database migrations'
  become_user: '{{ env.user }}'
  command: pnpm db:system:migrate
  args:
    chdir: '{{ env.directory }}'
  when: apps[app].migrations.system

- name: '{{ app|upper }} | Run foods database migrations'
  become_user: '{{ env.user }}'
  command: pnpm db:foods:migrate
  args:
    chdir: '{{ env.directory }}'
  when: apps[app].migrations.foods
