- name: Include shared vars
  include_vars: '../instances/{{ instance }}/shared/config.json'

- name: Update pm2 to latest
  command: npm install -g pm2

- name: Update in-memory pm2 code
  become_user: '{{ app.user }}'
  command: pm2 updatePM2

- name: Copy .env config file
  become_user: '{{ app.user }}'
  copy:
    src: '{{ env_file }}'
    dest: '{{ app.directory }}/apps/api/.env'
    mode: '644'

- name: Copy pm2 config file
  become_user: '{{ app.user }}'
  copy:
    src: '{{ pm2_file }}'
    dest: '{{ app.directory }}/apps/api/ecosystem.config.js'
    mode: '644'

- name: Build API server
  become_user: '{{ app.user }}'
  command: pnpm production
  args:
    chdir: '{{ app.directory }}/apps/api'

- name: Run foods database migrations
  become_user: '{{ app.user }}'
  command: pnpm db:migrate:foods
  when: migrations.foods

- name: Run system database migrations
  become_user: '{{ app.user }}'
  command: pnpm db:migrate:system
  when: migrations.system
