/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from 'util';
import Ajv = require('ajv');
import Config from './config';

export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export { Config };
export const ConfigSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  defaultProperties: [],
  properties: {
    batchSize: {
      type: 'number',
    },
    energyValueKcal: {
      type: 'number',
    },
    foodFilter: {
      items: {
        type: 'string',
      },
      type: 'array',
    },
    guideImageWidth: {
      type: 'number',
    },
    locale: {
      type: 'string',
    },
    portionSizeFilter: {
      items: {
        type: 'string',
      },
      type: 'array',
    },
  },
  required: [
    'batchSize',
    'energyValueKcal',
    'foodFilter',
    'guideImageWidth',
    'locale',
    'portionSizeFilter',
  ],
  type: 'object',
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
  Pick<Ajv.ValidateFunction, 'errors'>;
export const isConfig = ajv.compile(ConfigSchema) as ValidateFunction<Config>;
export default function validate(value: unknown): Config {
  if (isConfig(value)) {
    return value;
  }
  throw new Error(
    `${ajv.errorsText(
      isConfig.errors!.filter((e: any) => e.keyword !== 'if'),
      { dataVar: 'Config' }
    )}\n\n${inspect(value)}`
  );
}
