- name: '{{ app|upper }} | Set full service name'
  set_fact: 
    service_name: '{{ env.user }}-{{ apps[app].service.name }}'

- name: '{{ app|upper }} | Copy systemd service file'
  template:
    src: '{{ apps[app].service.template }}.service.j2'
    dest: '/lib/systemd/system/{{ service_name }}.service'
    owner: root
    group: root
    mode: '644'

#  TODO: might only reload pm2 processes for API server
# - name: Check if service is already running
#   shell: systemctl is-active {{ service_name }}
#   register: service_active
#   failed_when: false

- name: '{{ app|upper }} | Restart service to apply configuration changes'
  service:
    name: '{{ service_name }}'
    state: restarted
    enabled: yes
