- name: Copy .env config file
  become_user: '{{ env.user }}'
  copy:
    src: '{{ env_file }}'
    dest: '{{ env.directory }}/apps/docs/.env'
    mode: '600'

- name: Build client application
  become_user: '{{ env.user }}'
  command: pnpm build
  args:
    chdir: '{{ env.directory }}/apps/docs'
