<template>
  <v-container>
    <portion-layout :text="text" :description="description">
      <template v-slot:headerText>
        {{ $t('portion.cereal.label') }}
      </template>
      <v-row>
        <v-col>
          <v-expansion-panels v-model="panelOpenId">
            <v-expansion-panel>
              <v-expansion-panel-header disable-icon-rotate>
                Please select the bowl that looks most like the one you used.
                <template v-slot:actions>
                  <valid-invalid-icon :valid="bowlComplete"></valid-invalid-icon>
                </template>
              </v-expansion-panel-header>
              <v-expansion-panel-content>
                <!-- <v-img :src="bowlImageMapData.baseImageUrl" @click="selectBowlType()"></v-img>
                Image_maps gbowl -->
                <image-map-selector
                  :promptProps="{ imageMapId }"
                  @image-map-selector-submit="selectBowlType($event)"
                ></image-map-selector>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel>
              <v-expansion-panel-header disable-icon-rotate>
                Using these pictures, please choose how much chocolate hoops cereal you had.
                <template v-slot:actions>
                  <valid-invalid-icon :valid="asServedComplete"></valid-invalid-icon>
                </template>
              </v-expansion-panel-header>
              <v-expansion-panel-content>
                <as-served-selector
                  :asServedSetId="this.cerealType"
                  @as-served-selector-submit="setAsServedStatus($event)"
                ></as-served-selector>
                <!-- cereal_hoopA -->
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel>
              <v-expansion-panel-header disable-icon-rotate>
                Leftovers
                <template v-slot:actions>
                  <valid-invalid-icon :valid="leftoverComplete"></valid-invalid-icon>
                </template>
              </v-expansion-panel-header>
              <v-expansion-panel-content>
                <v-row>
                  <v-col>
                    <p>
                      {{ $t('portion.asServed.leftoverQuestion', { food: localeDescription }) }}
                    </p>
                    <v-btn @click="leftoverAnswer(true)">
                      {{ $t('common.confirm.yes') }}
                    </v-btn>
                    <v-btn @click="leftoverAnswer(false)">
                      {{ $t('common.confirm.no') }}
                    </v-btn>
                  </v-col>
                </v-row>

                <v-row v-if="showLeftovers">
                  <v-col>
                    <as-served-selector
                      :asServedSetId="this.cerealType"
                      @as-served-selector-submit="setLeftoverStatus($event)"
                    ></as-served-selector>
                  </v-col>
                </v-row>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel>
              <v-expansion-panel-header disable-icon-rotate>
                Did you have {associated food}? (TODO: generated by associatedPrompts array)
                <template v-slot:actions>
                  <valid-invalid-icon></valid-invalid-icon>
                </template>
              </v-expansion-panel-header>
              <v-expansion-panel-content>
                <v-btn @click="setAssocQuestionDisplay(0, true)">
                  {{ $t('common.confirm.yes') }}
                </v-btn>
                <v-btn @click="setAssocQuestionDisplay(0, false)">
                  {{ $t('common.confirm.no') }}
                </v-btn>
                <associated-food-panel
                  :promptProps="milkPromptProps"
                  v-if="displayAssocPrompt0"
                ></associated-food-panel>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <v-expansion-panel>
              <v-expansion-panel-header disable-icon-rotate>
                Did you have {associated food}? (TODO: generated by associatedPrompts array)
                <template v-slot:actions>
                  <valid-invalid-icon></valid-invalid-icon>
                </template>
              </v-expansion-panel-header>
              <v-expansion-panel-content>
                <v-btn @click="setAssocQuestionDisplay(1, true)">
                  {{ $t('common.confirm.yes') }}
                </v-btn>
                <v-btn @click="setAssocQuestionDisplay(1, false)">
                  {{ $t('common.confirm.no') }}
                </v-btn>
                <associated-food-panel
                  :promptProps="milkPromptProps"
                  v-if="displayAssocPrompt1"
                ></associated-food-panel>
              </v-expansion-panel-content>
            </v-expansion-panel>
            <!-- Probably makes sense to have a component for this the associated food prompts -->
          </v-expansion-panels>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-btn @click="submit()" :color="submitButtonStyle()">
            {{ $t('common.continue') }}
          </v-btn>
        </v-col>
      </v-row>
    </portion-layout>
  </v-container>
</template>

<script lang="ts">
import Vue, { VueConstructor } from 'vue';
import merge from 'deepmerge';
import {
  CerealPromptProps,
  cerealPromptDefaultProps,
  AssociatedFoodsPanelProps,
  ImageMapSelectorEmit,
} from '@common/prompts';
import { LocaleTranslation } from '@common/types';
import { UserFoodData } from '@common/types/http';
import AsServedSelector from '@/components/prompts/portion/selectors/AsServedSelector.vue';
import ImageMapSelector from '@/components/prompts/portion/selectors/ImageMapSelector.vue';
import AssociatedFoodPanel from '@/components/prompts/portion/AssociatedFoodPanel.vue';
import BaseExpansionPortion, { ExpansionPortion } from './BaseExpansionPortion';

export default (Vue as VueConstructor<Vue & ExpansionPortion>).extend({
  name: 'CerealPrompt',

  components: {
    AsServedSelector,
    AssociatedFoodPanel,
    ImageMapSelector,
  },

  mixins: [BaseExpansionPortion],

  props: {
    // Generic object 'props' used to store all props for each prompt
    promptProps: {
      type: Object as () => CerealPromptProps,
      required: true,
    },
    foodName: {
      type: Object as () => LocaleTranslation,
      required: true,
    },
    foodCode: {
      type: String,
      required: true,
    },
    imageMapId: {
      type: String,
      required: true,
    },
    localeTEMP: {
      type: String,
      required: true,
    },
  },

  data() {
    return {
      ...merge(cerealPromptDefaultProps, this.promptProps),
      errors: [] as string[],
      foodData: {} as UserFoodData,
      bowlTypeSelected: null as number | null,
      // asServedSetId: cereal_rkrisA
      // Foodcode: HNUT
      // Testing/prototyping variables
      // Couldn't find a mapping between imageMap objs and bowl A,B,C,D
      bowlTypeLookup: ['A', 'B', 'C', 'D'] as string[],
      cerealType: 'cereal_hoopA' as string,
      asServedData: [] as any,
      leftoverData: [] as any,
      bowlComplete: false as boolean,
      asServedComplete: false as boolean,
      leftoverComplete: false as boolean,
      showLeftovers: false as boolean,
      displayAssocPrompt0: false,
      displayAssocPrompt1: false,
      // Testing associated prompt
      milkPromptProps: {
        text: { en: 'milk' },
        description: { en: 'Did you have milk?' },
        conditions: [],
        validation: {
          required: false,
          message: { en: 'error' },
        },
        expansionPanelTotal: 3,
      } as AssociatedFoodsPanelProps,
      sugarPromptProps: {
        text: { en: 'milk' },
        description: { en: 'Did you have milk?' },
        conditions: [],
        validation: {
          required: false,
          message: { en: 'error' },
        },
        expansionPanelTotal: 3,
      } as AssociatedFoodsPanelProps,
    };
  },

  computed: {
    localeDescription(): string | null {
      return this.getLocaleContent(this.description);
    },
    hasErrors(): boolean {
      return !!this.errors.length;
    },
  },

  mounted() {
    this.fetchFoodData(); // Will also fetch associated prompts
  },

  methods: {
    async fetchFoodData() {
      try {
        const { data } = await this.$http.get(`foods/${this.localeTEMP}/${this.foodCode}`);
        this.foodData = { ...data };
      } catch (e) {
        console.log(e);
      }
    },

    async fetchAsServedData() {
      try {
        const { data } = await this.$http.get(`portion-sizes/as-served-sets/${this.cerealType}`);
        this.asServedData = { ...data };
      } catch (e) {
        console.log(e);
      }
    },

    async fetchLeftoverData() {
      try {
        const { data } = await this.$http.get(`portion-sizes/image-maps/${this.imageMapId}`);
        this.leftoverData = { ...data };
      } catch (e) {
        console.log(e);
      }
    },

    setAssocQuestionDisplay(questionId: number, newValue: boolean) {
      if (questionId === 0) {
        this.displayAssocPrompt0 = newValue;
      } else {
        this.displayAssocPrompt1 = newValue;
      }
    },

    leftoverAnswer(value: boolean) {
      if (value) {
        this.showLeftovers = true;
      } else {
        this.leftoverComplete = true;
        this.setPanelOpen(-1);
      }
    },

    selectBowlType(status: ImageMapSelectorEmit) {
      console.log(status);
      this.bowlTypeSelected = status.selectedIdx;
      this.bowlComplete = true;
      this.setPanelOpen(1);
      // Get as served now bowl is confirmed
    },

    // TODO: Implement emission type
    setAsServedStatus(status: Record<string, unknown>) {
      this.asServedComplete = true;
      this.setPanelOpen(2);
    },

    // TODO: Implement emission type
    setLeftoverStatus(status: Record<string, unknown>) {
      this.leftoverComplete = true;
      this.setPanelOpen(-1);
    },

    submitButtonStyle() {
      if (this.bowlComplete && this.asServedComplete && this.leftoverComplete) {
        return 'success';
      }
      return '';
    },
    submit() {
      if (this.bowlComplete && this.asServedComplete && this.leftoverComplete) {
        console.log('submitted');
      }
    },
  },
});
</script>

<style lang="scss" scoped>
.guides-drawer {
  position: relative;

  svg {
    position: absolute;
    top: 0;
    left: 0;

    .guides-drawer-polygon {
      cursor: pointer;
      fill: transparent;

      &.active,
      &:hover {
        fill: #0d47a1;
        fill-opacity: 0.4;
        stroke-width: 8;
        stroke: #0d47a1;
        stroke-linecap: round;
        stroke-linejoin: round;
        stroke-opacity: 0.5;
      }
    }
  }
}
</style>
