---
- hosts: admin
  remote_user: deploy
  become: true
  vars:
    app: 'admin'
  roles:
    - role: app-init
    - role: app-spa
    - role: app-service
      when: apps.admin.service.deploy | bool
    - role: app-end
