---
- hosts: survey
  remote_user: deploy
  become: true
  vars:
    app: 'survey'
  roles:
    - role: app-init
    - role: app-spa
    - role: app-service
      when: apps.survey.service.deploy | bool
