---
- hosts: webservers
  remote_user: deploy
  become: true
  roles:
    - deps-os
    - deps-nodejs
    - deps-nginx
    - deps-puppeteer

- hosts: redis
  remote_user: deploy
  become: true
  roles:
    - deps-redis
