---
- hosts: webservers
  remote_user: deploy
  become: true
  roles:
    - deps-os
    - deps-nodejs
    - deps-nginx

- hosts: api-server
  remote_user: deploy
  become: true
  roles:
    - deps-redis
