name: Docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'

jobs:
  docs-deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3.1.0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6

      - name: Use Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Docs - build
        run: pnpm docs:build

      - name: Set CNAME
        run: echo "docs.intake24.org" > docs/.vitepress/dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: ghp-docs
          folder: docs/.vitepress/dist
          clean: true
