name: Docs deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'apps/docs/**'

jobs:
  docs-build-deploy:
    name: Documentation

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2.4.0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Docs - build
        run: pnpm docs:build

      - name: Set CNAME
        run: echo "docs.intake24.co.uk" > docs/.vitepress/dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: ghp-docs
          folder: docs/.vitepress/dist
          clean: true
