name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'apps/docs/**'
      - 'packages/common/src/contracts/**'

permissions:
  contents: write

jobs:
  docs-deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Docs - build
        working-directory: apps/docs
        run: pnpm build

      - name: Set CNAME
        run: echo "docs.intake24.org" > apps/docs/.vitepress/dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ghp-docs
          folder: apps/docs/.vitepress/dist
          clean: true
